services:
  caddy:
    build: ./caddy
    ports:
      - "9001:80"
    depends_on:
      - springboot
  #  nginx:
  #    build: ./nginx
  #    container_name: nginx-proxy
  #    depends_on:
  #      - springboot
  #    ports:
  #      - "9000:80"
  #    volumes:
  #      - /home/linux-mint/IdeaProjects/volumes/nginx/html:/usr/share/nginx/html

  postgres:
    image: postgres:16-alpine
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - ${PGADMIN_PORTS}

    volumes:
      - pgadmin-data:/var/lib/pgadmin

  springboot:
    build:
      dockerfile: Dockerfile_QA
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    #      - MAIL_USERNAME=${MAIL_USERNAME}
    #      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
