server {
    listen 80;

    #server_name localhost wa-webrtc.onrender.com;
    location / {
        proxy_pass http://springboot:8080;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}