package de.thk.gm.fddw.lecturefaq.constants

const val MINIMUM_ANSWERS_COUNT = 2
const val MAXIMUM_ANSWERS_COUNT = 5
const val MINIMUM_TITLE_LENGTH = 1
const val MAXIMUM_TITLE_LENGTH = 100
const val MINIMUM_DESCRIPTION_LENGTH = 1
const val MAXIMUM_DESCRIPTION_LENGTH = 1_000
const val MINIMUM_TEXT_LENGTH = 1
const val MAXIMUM_TEXT_LENGTH = 1_000
const val MINIMUM_LINK_LENGTH  = 1
const val MAXIMUM_LINK_LENGTH  = 1_000
const val MINIMUM_NAME_LENGTH = 1
const val MAXIMUM_NAME_LENGTH = 100
const val MAXIMUM_EMAIL_LENGTH = 100
const val MINIMUM_PASSWORD_LENGTH = 5
const val MAXIMUM_PASSWORD_LENGTH = 50
const val MINIMUM_CODE_SIZE = 1
const val MAXIMUM_CODE_SIZE = 999
const val DUMMY_USER_ID = "00000000-0000-0000-0000-000000000000"